#!/usr/bin/env bash

# architecture name
# shellcheck disable=SC2155
export ARCH=$(uname -m)
export CPU_COUNT=$(sysctl -n hw.physicalcpu)
#export CACHE_LINE_SIZE=$(sysctl -n hw.cachelinesize)

# compiler and assembler
export CC="clang"
export CC_INFO="$($CC --version | head -n 1) ($(which $CC))"
export CFLAGS=("-arch arm64" "-std=c2x")
export ERR_CFLAGS=("-pedantic" "-Wall" "-Werror" "-Wno-newline-eof" "-Wno-gnu-binary-literal" "-Wno-error=unused-function" "-Wno-unused-function")
export OPT_CFLAGS=("-O3" "-flto")
export DEBUG_CFLAGS=("-O0" "-g" "-fdebug-macro")

export ASM="clang"
export ASM_INFO="$CC_INFO"
export ASMFLAGS=("-x" "assembler-with-cpp")

export DEBUGGER="lldb"
export DEBUG_FLAGS=()
export DEBUGGER_INFO="$($DEBUGGER --version | head -n 1) ($(which $DEBUGGER))"

export CHECK=""
export CHECK_FLAGS=""