#!/usr/bin/env bash

# shellcheck disable=SC2155
export ARCH=$(uname -m)
export CPU_COUNT=$(lscpu | grep '^CPU(s):' | awk '{print $2}')

export CC="gcc"
export CC_INFO="$($CC --version | head -n 1) ($(which $CC))"
export CFLAGS=()
export ERR_CFLAGS=("-pedantic" "-Wall" "-Werror")
export OPT_CFLAGS=("-O3" "-flto")
export DEBUG_CFLAGS=("-g")

export ASM="gcc"
export ASM_INFO="$CC_INFO"
export ASMFLAGS=("-x" "assembler-with-cpp")

export DEBUGGER="gdb"
export DEBUG_FLAGS=("-tui")
export DEBUGGER_INFO="$($DEBUGGER --version | head -n 1) ($(which $DEBUGGER))"