#!/usr/bin/env bash

# shellcheck disable=SC2155
export ARCH=$(uname -m)
export CPU_COUNT=$(lscpu | grep '^CPU(s):' | awk '{print $2}')

export CC="gcc"
export CC_INFO="$($CC --version | head -n 1) ($(which $CC))"
export CFLAGS=("-std=c2x")
export ERR_CFLAGS=("-pedantic" "-Wall" "-Werror" "-Wno-error=unused-function" "-Wno-unused-function")
export OPT_CFLAGS=("-O4" "-flto" "-fexpensive-optimizations")
export DEBUG_CFLAGS=("-O0" "-g")

export ASM="gcc"
export ASM_INFO="$CC_INFO"
export ASMFLAGS=("-x" "assembler-with-cpp")

export DEBUGGER="gdb"
export DEBUG_FLAGS=("-tui")
export DEBUGGER_INFO="$($DEBUGGER --version | head -n 1) ($(which $DEBUGGER))"

export CHECK="valgrind"
export CHECK_FLAGS="--leak-check=full --show-reachable=yes -s"